<?php
defined( 'ABSPATH' ) || exit;

final class SML_Language_Manager {
	private static $instance;
	public static function instance(){if(!self::$instance)self::$instance=new self();return self::$instance;}
	private function __construct(){add_action('admin_menu',array($this,'menu'),20);add_action('admin_post_sml_save_languages',array($this,'save'));}
	public function menu(){add_submenu_page('smart-multilingual',__('Manage Languages','smart-multilingual'),__('Manage Languages','smart-multilingual'),'manage_options','smart-multilingual-languages',array($this,'page'));}
	public function page(){if(!current_user_can('manage_options'))return;$registry=SML_Languages::registry();?>
	<div class="wrap sml-admin-wrap"><h1><?php esc_html_e('Manage Languages','smart-multilingual');?></h1>
	<div class="sml-card"><p><?php esc_html_e('The source language has an empty URL prefix and cannot be removed. Add other languages with unique prefixes.','smart-multilingual');?></p>
	<form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="sml_save_languages"><?php wp_nonce_field('sml_save_languages'); ?>
	<table class="widefat striped sml-language-table"><thead><tr><th><?php esc_html_e('Enabled','smart-multilingual');?></th><th><?php esc_html_e('Code','smart-multilingual');?></th><th><?php esc_html_e('English name','smart-multilingual');?></th><th><?php esc_html_e('Native name','smart-multilingual');?></th><th><?php esc_html_e('Locale','smart-multilingual');?></th><th><?php esc_html_e('URL prefix','smart-multilingual');?></th><th><?php esc_html_e('Direction','smart-multilingual');?></th><th><?php esc_html_e('hreflang','smart-multilingual');?></th><th></th></tr></thead><tbody id="sml-language-rows">
	<?php foreach($registry as$code=>$cfg)$this->row($code,$cfg); ?>
	</tbody></table><p><button type="button" class="button" id="sml-add-language"><?php esc_html_e('Add language','smart-multilingual');?></button></p><?php submit_button(__('Save languages','smart-multilingual'));?></form></div>
	<div class="sml-card"><h2><?php esc_html_e('Adding a language safely','smart-multilingual');?></h2><ol><li><?php esc_html_e('Add the language and save.','smart-multilingual');?></li><li><?php esc_html_e('Open Languages → Settings and choose switcher and menu options.','smart-multilingual');?></li><li><?php esc_html_e('Create translations from the Translations panel on posts, products and terms.','smart-multilingual');?></li><li><?php esc_html_e('Save Settings → Permalinks once if the new prefix does not open immediately.','smart-multilingual');?></li></ol></div></div>
	<script type="text/html" id="tmpl-sml-language-row"><?php $this->row('__CODE__',array('enabled'=>1,'name'=>'','native'=>'','locale'=>'','prefix'=>'','dir'=>'ltr','hreflang'=>''),true);?></script><?php }
	private function row($code,$cfg,$template=false){$locked=!$template&&SML_Languages::is_default($code);?><tr class="sml-language-row"><td><input type="checkbox" name="languages[<?php echo esc_attr($code);?>][enabled]" value="1" <?php checked(!empty($cfg['enabled']));?> <?php disabled($locked);?>><?php if($locked):?><input type="hidden" name="languages[<?php echo esc_attr($code);?>][enabled]" value="1"><?php endif;?></td><td><input class="small-text sml-language-code" type="text" name="languages[<?php echo esc_attr($code);?>][code]" value="<?php echo esc_attr($template?'':$code);?>" <?php echo $locked ? ' readonly="readonly"' : ''; ?> required></td><td><input type="text" name="languages[<?php echo esc_attr($code);?>][name]" value="<?php echo esc_attr($cfg['name']);?>" required></td><td><input type="text" name="languages[<?php echo esc_attr($code);?>][native]" value="<?php echo esc_attr($cfg['native']);?>" required></td><td><input class="small-text" type="text" name="languages[<?php echo esc_attr($code);?>][locale]" value="<?php echo esc_attr($cfg['locale']);?>" required></td><td><input class="small-text" type="text" name="languages[<?php echo esc_attr($code);?>][prefix]" value="<?php echo esc_attr($cfg['prefix']);?>" <?php echo $locked ? ' readonly="readonly"' : ''; ?>></td><td><select name="languages[<?php echo esc_attr($code);?>][dir]"><option value="ltr" <?php selected($cfg['dir'],'ltr');?>>LTR</option><option value="rtl" <?php selected($cfg['dir'],'rtl');?>>RTL</option></select></td><td><input class="small-text" type="text" name="languages[<?php echo esc_attr($code);?>][hreflang]" value="<?php echo esc_attr($cfg['hreflang']);?>" required></td><td><?php if(!$locked):?><button type="button" class="sml-danger-button sml-remove-language"><?php esc_html_e('Remove','smart-multilingual');?></button><?php endif;?></td></tr><?php }
	public function save(){if(!current_user_can('manage_options'))wp_die(esc_html__('Permission denied.','smart-multilingual'));check_admin_referer('sml_save_languages');$input=isset($_POST['languages'])&&is_array($_POST['languages'])?wp_unslash($_POST['languages']):array();$default=SML_Languages::default_code();$registry=array();$prefixes=array();$errors=array();foreach($input as$old=>$row){$code=sanitize_key($row['code']??$old);if(!$code)continue;if(isset($registry[$code])){$errors[]=sprintf(__('Duplicate language code: %s','smart-multilingual'),$code);continue;}$cfg=SML_Languages::sanitize_language($code,$row,$code===$default);if($code!==$default&&empty($cfg['prefix']))$cfg['prefix']=$code;if(in_array($cfg['prefix'],$prefixes,true)&&''!==$cfg['prefix']){$errors[]=sprintf(__('Duplicate URL prefix: %s','smart-multilingual'),$cfg['prefix']);continue;}$prefixes[]=$cfg['prefix'];$registry[$code]=$cfg;}if(empty($registry[$default]))$registry=array($default=>SML_Languages::get($default))+$registry;update_option(SML_Languages::OPTION_KEY,$registry,false);$settings=SML_Plugin::settings();$settings['default_language']=$default;$settings['enabled_languages']=array_keys(array_filter($registry,static function($c){return!empty($c['enabled']);}));$settings['switcher_languages']=array_values(array_intersect((array)$settings['switcher_languages'],$settings['enabled_languages']));update_option(SML_Plugin::OPTION_KEY,$settings,false);update_option('sml_rewrite_flush_required',1,false);$url=admin_url('admin.php?page=smart-multilingual-languages&updated=1');if($errors)$url=add_query_arg('sml_errors',rawurlencode(implode(' | ',$errors)),$url);wp_safe_redirect($url);exit;}
}
