<?php
defined( 'ABSPATH' ) || exit;

/** Portable per-site customization without theme-specific code in core. */
final class SML_Site_Profile {
	const OPTION_KEY = 'sml_site_profile';
	private static $instance;

	public static function instance() {
		if ( ! self::$instance ) self::$instance = new self();
		return self::$instance;
	}

	private function __construct() {
		add_action( 'admin_menu', array( $this, 'menu' ), 30 );
		add_action( 'admin_post_sml_save_site_profile', array( $this, 'save' ) );
		add_action( 'admin_post_sml_export_site_profile', array( $this, 'export' ) );
		add_action( 'admin_post_sml_import_site_profile', array( $this, 'import' ) );
		add_action( 'wp_enqueue_scripts', array( $this, 'frontend_css' ), 90 );
	}

	public static function get() {
		return wp_parse_args( (array) get_option( self::OPTION_KEY, array() ), array( 'name' => '', 'notes' => '', 'body_classes' => '', 'custom_css' => '' ) );
	}

	public function menu() {
		add_submenu_page( 'smart-multilingual', __( 'Site Profile', 'smart-multilingual' ), __( 'Site Profile', 'smart-multilingual' ), 'manage_options', 'smart-multilingual-site-profile', array( $this, 'page' ) );
	}

	public function page() {
		if ( ! current_user_can( 'manage_options' ) ) return;
		$p = self::get();
		?>
		<div class="wrap sml-admin-wrap"><h1><?php esc_html_e( 'Site Profile', 'smart-multilingual' ); ?></h1>
		<div class="sml-card sml-accent-blue"><h2><?php esc_html_e( 'Portable site customization', 'smart-multilingual' ); ?></h2><p><?php esc_html_e( 'Keep theme-specific CSS and notes here instead of editing plugin files. Export the profile to reuse it on another installation.', 'smart-multilingual' ); ?></p>
		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="sml_save_site_profile"><?php wp_nonce_field( 'sml_save_site_profile' ); ?>
		<table class="form-table"><tr><th><label for="sml-profile-name"><?php esc_html_e( 'Profile name', 'smart-multilingual' ); ?></label></th><td><input class="regular-text" id="sml-profile-name" name="profile[name]" value="<?php echo esc_attr( $p['name'] ); ?>"></td></tr>
		<tr><th><label for="sml-profile-classes"><?php esc_html_e( 'Extra body classes', 'smart-multilingual' ); ?></label></th><td><input class="large-text" id="sml-profile-classes" name="profile[body_classes]" value="<?php echo esc_attr( $p['body_classes'] ); ?>"><p class="description"><?php esc_html_e( 'Space-separated classes. Language classes are always generated by core.', 'smart-multilingual' ); ?></p></td></tr>
		<tr><th><label for="sml-profile-css"><?php esc_html_e( 'Profile CSS', 'smart-multilingual' ); ?></label></th><td><textarea class="large-text code" rows="16" id="sml-profile-css" name="profile[custom_css]"><?php echo esc_textarea( $p['custom_css'] ); ?></textarea></td></tr>
		<tr><th><label for="sml-profile-notes"><?php esc_html_e( 'Implementation notes', 'smart-multilingual' ); ?></label></th><td><textarea class="large-text" rows="6" id="sml-profile-notes" name="profile[notes]"><?php echo esc_textarea( $p['notes'] ); ?></textarea></td></tr></table>
		<?php submit_button( __( 'Save Site Profile', 'smart-multilingual' ) ); ?></form></div>
		<div class="sml-card sml-accent-green"><h2><?php esc_html_e( 'Import / export', 'smart-multilingual' ); ?></h2><p><?php esc_html_e( 'The JSON package contains configuration only; posts, products, users and media are never exported.', 'smart-multilingual' ); ?></p>
		<a class="button button-primary" href="<?php echo esc_url( wp_nonce_url( admin_url( 'admin-post.php?action=sml_export_site_profile' ), 'sml_export_site_profile' ) ); ?>"><?php esc_html_e( 'Export profile', 'smart-multilingual' ); ?></a>
		<form method="post" enctype="multipart/form-data" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sml-inline-import"><input type="hidden" name="action" value="sml_import_site_profile"><?php wp_nonce_field( 'sml_import_site_profile' ); ?><input type="file" name="profile_file" accept="application/json,.json" required><?php submit_button( __( 'Import profile', 'smart-multilingual' ), 'secondary', 'submit', false ); ?></form></div></div>
		<?php
	}

	public function save() {
		$this->authorize( 'sml_save_site_profile' );
		$input = isset( $_POST['profile'] ) && is_array( $_POST['profile'] ) ? wp_unslash( $_POST['profile'] ) : array();
		update_option( self::OPTION_KEY, self::sanitize( $input ), false );
		wp_safe_redirect( add_query_arg( 'updated', '1', admin_url( 'admin.php?page=smart-multilingual-site-profile' ) ) ); exit;
	}

	public function export() {
		$this->authorize( 'sml_export_site_profile' );
		$data = array(
			'format' => 'smart-multilingual-site-profile', 'version' => 1, 'plugin_version' => SML_VERSION,
			'profile' => self::get(), 'settings' => SML_Plugin::settings(), 'languages' => SML_Languages::registry(),
			'strings' => $this->string_options(), 'slider_mappings' => get_option( 'sml_revslider_mappings', array() ),
		);
		nocache_headers(); header( 'Content-Type: application/json; charset=utf-8' ); header( 'Content-Disposition: attachment; filename="smart-multilingual-site-profile.json"' );
		echo wp_json_encode( $data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ); exit;
	}

	public function import() {
		$this->authorize( 'sml_import_site_profile' );
		$file = isset( $_FILES['profile_file'] ) && is_array( $_FILES['profile_file'] ) ? $_FILES['profile_file'] : array(); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
		$tmp  = isset( $file['tmp_name'] ) ? (string) $file['tmp_name'] : '';
		$size = isset( $file['size'] ) ? absint( $file['size'] ) : 0;
		if ( '' === $tmp || ! is_uploaded_file( $tmp ) ) wp_die( esc_html__( 'Profile file was not uploaded.', 'smart-multilingual' ) );
		if ( $size < 1 || $size > 2 * MB_IN_BYTES ) wp_die( esc_html__( 'The Site Profile file must be smaller than 2 MB.', 'smart-multilingual' ) );
		$raw = file_get_contents( $tmp ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		$data = json_decode( (string) $raw, true );
		if ( ! is_array( $data ) || 'smart-multilingual-site-profile' !== ( $data['format'] ?? '' ) || 1 !== absint( $data['version'] ?? 0 ) ) wp_die( esc_html__( 'Invalid or unsupported Site Profile file.', 'smart-multilingual' ) );
		if ( isset( $data['profile'] ) ) update_option( self::OPTION_KEY, self::sanitize( (array) $data['profile'] ), false );
		if ( isset( $data['languages'] ) && is_array( $data['languages'] ) ) update_option( SML_Languages::OPTION_KEY, $this->sanitize_languages( $data['languages'] ), false );
		if ( isset( $data['settings'] ) && is_array( $data['settings'] ) ) {
			$merged = array_replace_recursive( SML_Plugin::settings(), $data['settings'] );
			update_option( SML_Plugin::OPTION_KEY, SML_Admin::instance()->sanitize_settings( $merged ), false );
		}
		foreach ( (array) ( $data['strings'] ?? array() ) as $key => $value ) if ( 0 === strpos( $key, 'sml_' ) ) update_option( sanitize_key( $key ), sanitize_textarea_field( (string) $value ), false );
		if ( isset( $data['slider_mappings'] ) ) update_option( 'sml_revslider_mappings', $this->sanitize_slider_mappings( (array) $data['slider_mappings'] ), false );
		update_option( 'sml_rewrite_flush_required', 1, false );
		wp_safe_redirect( add_query_arg( 'imported', '1', admin_url( 'admin.php?page=smart-multilingual-site-profile' ) ) ); exit;
	}

	public function frontend_css() {
		$css = trim( (string) self::get()['custom_css'] );
		if ( '' !== $css ) wp_add_inline_style( 'sml-frontend', $css );
	}

	public static function body_classes() {
		return preg_split( '/\s+/', trim( (string) self::get()['body_classes'] ) ) ?: array();
	}

	private static function sanitize( $input ) {
		return array( 'name' => sanitize_text_field( $input['name'] ?? '' ), 'notes' => sanitize_textarea_field( $input['notes'] ?? '' ), 'body_classes' => implode( ' ', array_filter( array_map( 'sanitize_html_class', preg_split( '/\s+/', (string) ( $input['body_classes'] ?? '' ) ) ) ) ), 'custom_css' => wp_strip_all_tags( (string) ( $input['custom_css'] ?? '' ) ) );
	}

	private function sanitize_languages( $input ) {
		$output       = array();
		$source_found = false;
		foreach ( $input as $code => $config ) {
			$code = sanitize_key( $code );
			if ( ! $code || ! is_array( $config ) ) continue;
			$is_source = ! $source_found && '' === trim( (string) ( $config['prefix'] ?? '' ) );
			$output[ $code ] = SML_Languages::sanitize_language( $code, $config, $is_source );
			if ( $is_source ) $source_found = true;
		}
		if ( ! $output ) return SML_Languages::initial_registry();
		if ( ! $source_found ) {
			$first = array_key_first( $output );
			$output[ $first ] = SML_Languages::sanitize_language( $first, $output[ $first ], true );
		}
		return $output;
	}

	private function sanitize_slider_mappings( $input ) {
		$output = array();
		$seen   = array();
		foreach ( $input as $mapping ) {
			if ( ! is_array( $mapping ) ) continue;
			$source = preg_replace( '/[^A-Za-z0-9_.:-]/', '', sanitize_text_field( (string) ( $mapping['source'] ?? '' ) ) );
			if ( ! $source || isset( $seen[ $source ] ) ) continue;
			$translations = array();
			foreach ( (array) ( $mapping['translations'] ?? array() ) as $language => $alias ) {
				$language = sanitize_key( $language );
				$alias    = preg_replace( '/[^A-Za-z0-9_.:-]/', '', sanitize_text_field( (string) $alias ) );
				if ( $language && $alias ) $translations[ $language ] = $alias;
			}
			$output[] = array( 'source' => $source, 'translations' => $translations );
			$seen[ $source ] = true;
		}
		return $output;
	}

	private function authorize( $nonce ) { if ( ! current_user_can( 'manage_options' ) ) wp_die( esc_html__( 'Permission denied.', 'smart-multilingual' ) ); check_admin_referer( $nonce ); }
	private function string_options() { $out = array(); foreach ( SML_Languages::secondary() as $lang ) foreach ( array( 'sml_string_translations_', 'sml_language_only_strings_', 'sml_attribute_translations_', 'sml_scoped_strings_', 'sml_sidebar_map_' ) as $prefix ) $out[ $prefix . $lang ] = (string) get_option( $prefix . $lang, '' ); return $out; }
}
